More verbose output, separate bans from fails
Add HTTP and Curl response codes in a new status column to diffrentiate
from actual bans vs the numerous different errors that could be returned

Now adds bans to a separate file instead of lumping them in with general
failures which could just be a simple proxy timeout.

diff --git a/bancheck b/bancheck
--- a/bancheck
+++ b/bancheck
@@ -8,10 +8,15 @@
 # Use the following format:
 # protocol://user:password@ip:port
 #
-# The script will append proxies to proxies_[good|bad].txt
-# You'll have the option to clear those before it starts.
+# Proxies are added to proxies_[good|bad|banned].txt based on
+# whether they receive a 200 (good), 403/9 (banned) or other.
+# You'll have the option to clear the files before it starts.
 #
 # To adjust the time between proxy checks, adjust MaxDelay.
+#
+# Find me on Discord @Galactica#7178
+# Found this script useful? Buy me a beer:
+# https://www.paypal.me/GalacticaPogo
 #
 
 MaxDelay=5
@@ -25,7 +30,7 @@ if [ ! -f proxies.txt ]; then
     exit
 fi
 
-for file in proxies_bad.txt proxies_good.txt; do
+for file in proxies_bad.txt proxies_banned.txt proxies_good.txt; do
     if [ -f $file ]; then
         read -rp "Remove ${file} before starting? [y/N] " response
         case "$response" in
@@ -43,40 +48,52 @@ echo
 echo "Beginning PoGo/PTC ban check for ${total} proxies..."
 
 declare -i pogo_fail
+declare -i pogo_bans
 declare -i ptc_fail
+declare -i ptc_bans
 
-printf "\n %-${longest}s   PoGo   PTC\n" 'Proxy'
+printf "\n %-${longest}s   PoGo [ Status ]  PTC [ Status ]\n" 'Proxy'
 
 while read proxy; do
     BAD=false
+    BAN=false
+
     printf " %-${longest}s  " $proxy
 
     sleep $[($RANDOM % 5) + 1]s
 
     # Begin PoGo check
     response=$(curl -sw 'HTTP_STATUS:%{http_code}' -A "$UserAgent" -x "$proxy" $PogoUrl)
-    if [ $? -eq 0]; then
+    exit_code=$?
+    if [ $exit_code -eq 0 ]; then
         status=$(echo $response | tr -d '\n' | sed -e 's/.*HTTP_STATUS://')
 
-        if [ $status -eq 403 ]; then BAD=true; pogo_fail+=1; echo -n ' FAIL'
+        if [ $status -eq 403 ]; then BAN=true; pogo_bans+=1; echo -n ' BAN!'
         elif [ $status -eq 200 ]; then echo -n ' PASS'
         else BAD=true; pogo_fail+=1; echo -n ' FAIL'; fi
-    else BAD=true; pogo_fail+=1; echo -n ' FAIL'; fi
+
+        echo -n " [HTTP:$status]"
+    else BAD=true; pogo_fail+=1; printf " FAIL [CURL:%3s]" $exit_code; fi
 
     sleep $[($RANDOM % 5) + 1]s
 
     # Begin PTC check
     response=$(curl -sw 'HTTP_STATUS:%{http_code}' -A "$UserAgent" -x "$proxy" $PtcUrl)
-    if [ $? -eq 0 ]; then
+    exit_code=$?
+    if [ $exit_code -eq 0 ]; then
         status=$(echo $response | tr -d '\n' | sed -e 's/.*HTTP_STATUS://')
 
-        if [ $status -eq 409 ]; then BAD=true; ptc_fail+=1; echo ' FAIL'
-        elif [ $status -eq 200 ]; then echo ' PASS'
-        else BAD=true; ptc_fail+=1; echo ' FAIL'; fi
-    else BAD=true; ptc_fail+=1; echo ' FAIL'; fi
+        if [ $status -eq 409 ]; then BAN=true; ptc_bans+=1; echo -n ' BAN!'
+        elif [ $status -eq 200 ]; then echo -n ' PASS'
+        else BAD=true; ptc_fail+=1; echo -n ' FAIL'; fi
+
+        echo " [HTTP:${status}]"
+    else BAD=true; ptc_fail+=1; printf " FAIL [CURL:%3s]\n" $exit_code; fi
 
     if $BAD; then
         echo "$proxy" >> proxies_bad.txt
+    elif $BAN; then
+        echo "$proxy" >> proxies_banned.txt
     else
         echo "$proxy" >> proxies_good.txt
     fi
@@ -84,14 +101,9 @@ done < proxies.txt
 
 echo
 echo "Proxy check complete!"
-if (( pogo_fail > 0 )); then
-    echo "$pogo_fail of $total proxies are banned from PokemonGO."
-else
-    echo "No proxies are banned from PokemonGO!"
-fi
 
-if (( ptc_fail > 0 )); then
-    echo "$ptc_fail of $total proxies are banned from PTC."
-else
-    echo "No proxies are banned from PTC!"
-fi
+pogo_good=$((total - pogo_bans - pogo_fail))
+ptc_good=$((total - ptc_bans - ptc_fail))
+
+echo "PokemonGO has $pogo_bans/$total bans, $pogo_good good accounts and $pogo_fail other failures."
+echo "PTC has $ptc_bans/$total bans, $ptc_good good accounts and $ptc_fail other failures."
